
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ZoneStatus
    {
        /// <summary>
        /// 开启
        /// </summary>
        Active = 0,

        /// <summary>
        /// 关闭
        /// </summary>
        Closed = 1,

    }
}
