
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ActionsConfig : BeanBase
    {
        public ActionsConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Param = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Param[__index0] = __e0;}}

            PostInit();
        }

        public static ActionsConfig DeserializeActionsConfig(ByteBuf _buf)
        {
            return new ActionsConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能行为类型
        /// </summary>
        public readonly int Type;

        /// <summary>
        /// 参数
        /// </summary>
        public readonly string[] Param;

        public const int __ID__ = 1530295935;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Param:" + Luban.StringUtil.CollectionToString(Param) + ","
            + "}";
        }

        partial void PostInit();
    }
}
