
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : BeanBase
    {
        public BuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NoticeClientType = (NoticeClientType)_buf.ReadInt();
            TotalTime = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AddAction = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); AddAction[__index0] = __e0;}}
            TickTime = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TickAction = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TickAction[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RemoveAction = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RemoveAction[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OwnerEffect = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); OwnerEffect[__index0] = __e0;}}

            PostInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 通知客户端类型
        /// </summary>
        public readonly NoticeClientType NoticeClientType;

        /// <summary>
        /// 总时长
        /// </summary>
        public readonly int TotalTime;

        /// <summary>
        /// 效果
        /// </summary>
        public readonly int[] AddAction;

        /// <summary>
        /// Tick间隔时间
        /// </summary>
        public readonly int TickTime;

        /// <summary>
        /// 效果
        /// </summary>
        public readonly int[] TickAction;

        /// <summary>
        /// 效果
        /// </summary>
        public readonly int[] RemoveAction;

        /// <summary>
        /// Buff自身特效
        /// </summary>
        public readonly int[] OwnerEffect;

        public const int __ID__ = -1370631787;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NoticeClientType:" + NoticeClientType + ","
            + "TotalTime:" + TotalTime + ","
            + "AddAction:" + Luban.StringUtil.CollectionToString(AddAction) + ","
            + "TickTime:" + TickTime + ","
            + "TickAction:" + Luban.StringUtil.CollectionToString(TickAction) + ","
            + "RemoveAction:" + Luban.StringUtil.CollectionToString(RemoveAction) + ","
            + "OwnerEffect:" + Luban.StringUtil.CollectionToString(OwnerEffect) + ","
            + "}";
        }

        partial void PostInit();
    }
}
