//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class DifficultyHappyCategroy: Singleton<DifficultyHappyCategroy>,IMerge
{
    private Dictionary<int, DifficultyHappyConfig> _dataMap;
    private List<DifficultyHappyConfig> _dataList;

    public DifficultyHappyCategroy(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, DifficultyHappyConfig>();
        _dataList = new List<DifficultyHappyConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DifficultyHappyConfig _v;
            _v = DifficultyHappyConfig.DeserializeDifficultyHappyConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, DifficultyHappyConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<DifficultyHappyConfig> DataList => _dataList;

    public void Merge(object o)
    {
        DifficultyHappyCategroy s = o as DifficultyHappyCategroy;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public DifficultyHappyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DifficultyHappyConfig Get(int key) => _dataMap[key];
    public DifficultyHappyConfig this[int key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(DifficultyHappyConfig).Name;
    }
}
}