
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DifficultyNormalConfig : BeanBase
    {
        public DifficultyNormalConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Desc = _buf.ReadString();
            WaveNumber = _buf.ReadInt();
            HasSecond = _buf.ReadBool();

            PostInit();
        }

        public static DifficultyNormalConfig DeserializeDifficultyNormalConfig(ByteBuf _buf)
        {
            return new DifficultyNormalConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 波数
        /// </summary>
        public readonly int WaveNumber;

        /// <summary>
        /// 是否有第二幕
        /// </summary>
        public readonly bool HasSecond;

        public const int __ID__ = 580228;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Desc:" + Desc + ","
            + "WaveNumber:" + WaveNumber + ","
            + "HasSecond:" + HasSecond + ","
            + "}";
        }

        partial void PostInit();
    }
}
