//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class LocalizeConfig_CHS :  ALocalizeConfig 
{
    public LocalizeConfig_CHS(ByteBuf _buf)  : base(_buf) 
    {
        TextCHS = _buf.ReadString();
        this.EndInit();
    }

    public static LocalizeConfig_CHS DeserializeLocalizeConfig_CHS(ByteBuf _buf)
    {
        return new LocalizeConfig_CHS(_buf);
    }

    public string TextCHS { get; set; }

    public const int __ID__ = -887446246;
    public int GetTypeId() => __ID__;
}
}