//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class LocalizeConfig_CHT :  ALocalizeConfig 
{
    public LocalizeConfig_CHT(ByteBuf _buf)  : base(_buf) 
    {
        TextCHT = _buf.ReadString();
    }

    public static LocalizeConfig_CHT DeserializeLocalizeConfig_CHT(ByteBuf _buf)
    {
        return new LocalizeConfig_CHT(_buf);
    }

    public string TextCHT { get; set; }

    public const int __ID__ = -887446245;
    public int GetTypeId() => __ID__;
}
}