//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class LocalizeConfig_Excel_ENCategory: Singleton<LocalizeConfig_Excel_ENCategory>,IMerge
{
    private Dictionary<string, LocalizeConfig_EN> _dataMap;
    private List<LocalizeConfig_EN> _dataList;

    public LocalizeConfig_Excel_ENCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, LocalizeConfig_EN>();
        _dataList = new List<LocalizeConfig_EN>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LocalizeConfig_EN _v;
            _v = LocalizeConfig_EN.DeserializeLocalizeConfig_EN(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }
    
    public bool Contain(string id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<string, LocalizeConfig_EN> GetAll()
    {
        return _dataMap;
    }
    
    public List<LocalizeConfig_EN> DataList => _dataList;

    public void Merge(object o)
    {
        LocalizeConfig_Excel_ENCategory s = o as LocalizeConfig_Excel_ENCategory;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public LocalizeConfig_EN GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocalizeConfig_EN Get(string key) => _dataMap[key];
    public LocalizeConfig_EN this[string key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(LocalizeConfig_EN).Name;
    }
}
}