
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ModelConfig : BeanBase
    {
        public ModelConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Desc = _buf.ReadString();
            DifficultyType = _buf.ReadInt();

            PostInit();
        }

        public static ModelConfig DeserializeModelConfig(ByteBuf _buf)
        {
            return new ModelConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 难度类型
        /// </summary>
        public readonly int DifficultyType;

        public const int __ID__ = 1694060459;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Desc:" + Desc + ","
            + "DifficultyType:" + DifficultyType + ","
            + "}";
        }

        partial void PostInit();
    }
}
