
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterGroupConfig : BeanBase
    {
        public MonsterGroupConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            PosX = _buf.ReadFloat();
            PosY = _buf.ReadFloat();
            PosZ = _buf.ReadFloat();
            Range = _buf.ReadInt();

            PostInit();
        }

        public static MonsterGroupConfig DeserializeMonsterGroupConfig(ByteBuf _buf)
        {
            return new MonsterGroupConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 位置X
        /// </summary>
        public readonly float PosX;

        /// <summary>
        /// 位置Y
        /// </summary>
        public readonly float PosY;

        /// <summary>
        /// 位置Z
        /// </summary>
        public readonly float PosZ;

        /// <summary>
        /// 范围
        /// </summary>
        public readonly int Range;

        public const int __ID__ = -1205282169;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PosX:" + PosX + ","
            + "PosY:" + PosY + ","
            + "PosZ:" + PosZ + ","
            + "Range:" + Range + ","
            + "}";
        }

        partial void PostInit();
    }
}
