//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class UnitConfig : ProtoObject
{
    public UnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Name_l10n_key = _buf.ReadString(); Name = _buf.ReadString();
        Position = _buf.ReadInt();
        Height = _buf.ReadInt();
        this.EndInit();
    }

    public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
    {
        return new UnitConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// Type
    /// </summary>
    public int Type { get; set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; set; }
    public string Name_l10n_key { get; }
    /// <summary>
    /// 位置
    /// </summary>
    public int Position { get; set; }
    /// <summary>
    ///  
    /// </summary>
    public int Height { get; set; }

    public const int __ID__ = -568528378;
    public int GetTypeId() => __ID__;
}
}