//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public abstract partial class ALocalizeConfig : ProtoObject
{
    public ALocalizeConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
    }

    public static ALocalizeConfig DeserializeALocalizeConfig(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case LocalizeConfig_CHS.__ID__: return new LocalizeConfig_CHS(_buf);
            case LocalizeConfig_CHT.__ID__: return new LocalizeConfig_CHT(_buf);
            case LocalizeConfig_EN.__ID__: return new LocalizeConfig_EN(_buf);
            default: throw new SerializationException();
        }
    }

    public string Key { get; set; }

}
}