//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class DifficultyNormalConfig : ProtoObject
{
    public DifficultyNormalConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        WaveNumber = _buf.ReadInt();
        HasSecond = _buf.ReadBool();
    }

    public static DifficultyNormalConfig DeserializeDifficultyNormalConfig(ByteBuf _buf)
    {
        return new DifficultyNormalConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    ///  
    /// </summary>
    public int WaveNumber { get; set; }
    public bool HasSecond { get; set; }

    public const int __ID__ = 580228;
    public int GetTypeId() => __ID__;
}
}