//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class DifficultyNormalCategory: Singleton<DifficultyNormalCategory>,IMerge
{
    private Dictionary<int, DifficultyNormalConfig> _dataMap;
    private List<DifficultyNormalConfig> _dataList;

    public DifficultyNormalCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, DifficultyNormalConfig>();
        _dataList = new List<DifficultyNormalConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DifficultyNormalConfig _v;
            _v = DifficultyNormalConfig.DeserializeDifficultyNormalConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, DifficultyNormalConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<DifficultyNormalConfig> DataList => _dataList;

    public void Merge(object o)
    {
        DifficultyNormalCategory s = o as DifficultyNormalCategory;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public DifficultyNormalConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DifficultyNormalConfig Get(int key) => _dataMap[key];
    public DifficultyNormalConfig this[int key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(DifficultyNormalConfig).Name;
    }
}
}