//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class HeroCategory: Singleton<HeroCategory>,IMerge
{
    private Dictionary<int, HeroConfig> _dataMap;
    private List<HeroConfig> _dataList;

    public HeroCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, HeroConfig>();
        _dataList = new List<HeroConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            HeroConfig _v;
            _v = HeroConfig.DeserializeHeroConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, HeroConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<HeroConfig> DataList => _dataList;

    public void Merge(object o)
    {
        HeroCategory s = o as HeroCategory;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public HeroConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroConfig Get(int key) => _dataMap[key];
    public HeroConfig this[int key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(HeroConfig).Name;
    }
}
}