//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class LocalizeConfig_EN :  ALocalizeConfig 
{
    public LocalizeConfig_EN(ByteBuf _buf)  : base(_buf) 
    {
        TextEN = _buf.ReadString();
        this.EndInit();
    }

    public static LocalizeConfig_EN DeserializeLocalizeConfig_EN(ByteBuf _buf)
    {
        return new LocalizeConfig_EN(_buf);
    }

    public string TextEN { get; set; }

    public const int __ID__ = 2049582749;
    public int GetTypeId() => __ID__;
}
}