
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum MainType
    {
        /// <summary>
        /// 力量
        /// </summary>
        Strength = 0,

        /// <summary>
        /// 敏捷
        /// </summary>
        Agile = 1,

        /// <summary>
        /// 智力
        /// </summary>
        Magic = 2,

    }
}
