
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MapConfigCategory : Singleton<MapConfigCategory>
    {
        private readonly Dictionary<int, MapConfig> _dataMap;
        private readonly List<MapConfig> _dataList;

        public MapConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MapConfig>();
            _dataList = new List<MapConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MapConfig _v;
                _v = MapConfig.DeserializeMapConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MapConfig> DataMap => _dataMap;
        public List<MapConfig> DataList => _dataList;

        public MapConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public MapConfig Get(int key) => _dataMap[key];
        public MapConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
