
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MapConfig : BeanBase
    {
        public MapConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            IsBattleMap = _buf.ReadBool();
            StartSceneConfigId = _buf.ReadInt();
            BirthPosX = _buf.ReadFloat();
            BirthPosY = _buf.ReadFloat();
            BirthPosZ = _buf.ReadFloat();
            ResourcePath = _buf.ReadString();

            PostInit();
        }

        public static MapConfig DeserializeMapConfig(ByteBuf _buf)
        {
            return new MapConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 是否为战斗地图
        /// </summary>
        public readonly bool IsBattleMap;

        /// <summary>
        /// Map服务器配置Id
        /// </summary>
        public readonly int StartSceneConfigId;

        /// <summary>
        /// 出生位置X
        /// </summary>
        public readonly float BirthPosX;

        /// <summary>
        /// 出生位置Y
        /// </summary>
        public readonly float BirthPosY;

        /// <summary>
        /// 出生位置Z
        /// </summary>
        public readonly float BirthPosZ;

        /// <summary>
        /// 资源路径
        /// </summary>
        public readonly string ResourcePath;

        public const int __ID__ = -1840922722;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "IsBattleMap:" + IsBattleMap + ","
            + "StartSceneConfigId:" + StartSceneConfigId + ","
            + "BirthPosX:" + BirthPosX + ","
            + "BirthPosY:" + BirthPosY + ","
            + "BirthPosZ:" + BirthPosZ + ","
            + "ResourcePath:" + ResourcePath + ","
            + "}";
        }

        partial void PostInit();
    }
}
