//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class ModelConfig : ProtoObject
{
    public ModelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        DifficultyType = _buf.ReadInt();
    }

    public static ModelConfig DeserializeModelConfig(ByteBuf _buf)
    {
        return new ModelConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; set; }
    /// <summary>
    ///  
    /// </summary>
    public int DifficultyType { get; set; }

    public const int __ID__ = 1694060459;
    public int GetTypeId() => __ID__;
}
}