//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class ModelCategory: Singleton<ModelCategory>,IMerge
{
    private Dictionary<int, ModelConfig> _dataMap;
    private List<ModelConfig> _dataList;

    public ModelCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, ModelConfig>();
        _dataList = new List<ModelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ModelConfig _v;
            _v = ModelConfig.DeserializeModelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, ModelConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<ModelConfig> DataList => _dataList;

    public void Merge(object o)
    {
        ModelCategory s = o as ModelCategory;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public ModelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ModelConfig Get(int key) => _dataMap[key];
    public ModelConfig this[int key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(ModelConfig).Name;
    }
}
}