
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ParticleConfigCategory : Singleton<ParticleConfigCategory>
    {
        private readonly Dictionary<int, ParticleConfig> _dataMap;
        private readonly List<ParticleConfig> _dataList;

        public ParticleConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ParticleConfig>();
            _dataList = new List<ParticleConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ParticleConfig _v;
                _v = ParticleConfig.DeserializeParticleConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ParticleConfig> DataMap => _dataMap;
        public List<ParticleConfig> DataList => _dataList;

        public ParticleConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ParticleConfig Get(int key) => _dataMap[key];
        public ParticleConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
