
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ParticleConfig : BeanBase
    {
        public ParticleConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            PrefabName = _buf.ReadString();
            TotalTime = _buf.ReadInt();
            IsFollowUnit = _buf.ReadInt();
            PosX = _buf.ReadFloat();
            PosY = _buf.ReadFloat();
            PosZ = _buf.ReadFloat();
            ScaleX = _buf.ReadFloat();
            ScaleY = _buf.ReadFloat();
            ScaleZ = _buf.ReadFloat();
            ResourcePath = _buf.ReadString();

            PostInit();
        }

        public static ParticleConfig DeserializeParticleConfig(ByteBuf _buf)
        {
            return new ParticleConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 特效资源名称
        /// </summary>
        public readonly string PrefabName;

        /// <summary>
        /// 存在时长
        /// </summary>
        public readonly int TotalTime;

        /// <summary>
        /// 是否跟随
        /// </summary>
        public readonly int IsFollowUnit;

        /// <summary>
        /// 初始位置X
        /// </summary>
        public readonly float PosX;

        /// <summary>
        /// 初始位置Y
        /// </summary>
        public readonly float PosY;

        /// <summary>
        /// 初始位置Z
        /// </summary>
        public readonly float PosZ;

        /// <summary>
        /// 缩放X
        /// </summary>
        public readonly float ScaleX;

        /// <summary>
        /// 缩放Y
        /// </summary>
        public readonly float ScaleY;

        /// <summary>
        /// 缩放Z
        /// </summary>
        public readonly float ScaleZ;

        /// <summary>
        /// 资源路径
        /// </summary>
        public readonly string ResourcePath;

        public const int __ID__ = -1933562488;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PrefabName:" + PrefabName + ","
            + "TotalTime:" + TotalTime + ","
            + "IsFollowUnit:" + IsFollowUnit + ","
            + "PosX:" + PosX + ","
            + "PosY:" + PosY + ","
            + "PosZ:" + PosZ + ","
            + "ScaleX:" + ScaleX + ","
            + "ScaleY:" + ScaleY + ","
            + "ScaleZ:" + ScaleZ + ","
            + "ResourcePath:" + ResourcePath + ","
            + "}";
        }

        partial void PostInit();
    }
}
