//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class RandomName : ProtoObject
{
    public RandomName(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameCN = _buf.ReadString();
        NameEN = _buf.ReadString();
        this.EndInit();
    }

    public static RandomName DeserializeRandomName(ByteBuf _buf)
    {
        return new RandomName(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 中文名称
    /// </summary>
    public string NameCN { get; set; }
    /// <summary>
    /// 英文名称
    /// </summary>
    public string NameEN { get; set; }

    public const int __ID__ = 2108921358;
    public int GetTypeId() => __ID__;
}
}