//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class ResourceMonsterCategory: Singleton<ResourceMonsterCategory>,IMerge
{
    private Dictionary<int, ResourceMonsterConfig> _dataMap;
    private List<ResourceMonsterConfig> _dataList;

    public ResourceMonsterCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, ResourceMonsterConfig>();
        _dataList = new List<ResourceMonsterConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ResourceMonsterConfig _v;
            _v = ResourceMonsterConfig.DeserializeResourceMonsterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, ResourceMonsterConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<ResourceMonsterConfig> DataList => _dataList;

    public void Merge(object o)
    {
        ResourceMonsterCategory s = o as ResourceMonsterCategory;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public ResourceMonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ResourceMonsterConfig Get(int key) => _dataMap[key];
    public ResourceMonsterConfig this[int key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(ResourceMonsterConfig).Name;
    }
}
}