
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ResourceMonsterCategory : Singleton<ResourceMonsterCategory>
    {
        private readonly Dictionary<int, ResourceMonsterConfig> _dataMap;
        private readonly List<ResourceMonsterConfig> _dataList;

        public ResourceMonsterCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ResourceMonsterConfig>();
            _dataList = new List<ResourceMonsterConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ResourceMonsterConfig _v;
                _v = ResourceMonsterConfig.DeserializeResourceMonsterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ResourceMonsterConfig> DataMap => _dataMap;
        public List<ResourceMonsterConfig> DataList => _dataList;

        public ResourceMonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ResourceMonsterConfig Get(int key) => _dataMap[key];
        public ResourceMonsterConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
