//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class StartSceneConfig : ProtoObject
{
    public StartSceneConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Process = _buf.ReadInt();
        Zone = _buf.ReadInt();
        SceneType = _buf.ReadString();
        Name = _buf.ReadString();
        Port = _buf.ReadInt();
    }

    public static StartSceneConfig DeserializeStartSceneConfig(ByteBuf _buf)
    {
        return new StartSceneConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 所属进程
    /// </summary>
    public int Process { get; set; }
    /// <summary>
    /// 所属区
    /// </summary>
    public int Zone { get; set; }
    /// <summary>
    /// 类型
    /// </summary>
    public string SceneType { get; set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; set; }
    /// <summary>
    /// 外网端口
    /// </summary>
    public int Port { get; set; }

    public const int __ID__ = 1499456844;
    public int GetTypeId() => __ID__;
}
}