//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class StartZoneConfig : ProtoObject
{
    public StartZoneConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DBConnection = _buf.ReadString();
        DBName = _buf.ReadString();
        Desc = _buf.ReadString();
        this.EndInit();
    }

    public static StartZoneConfig DeserializeStartZoneConfig(ByteBuf _buf)
    {
        return new StartZoneConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 数据库地址
    /// </summary>
    public string DBConnection { get; set; }
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DBName { get; set; }
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc { get; set; }

    public const int __ID__ = -457316368;
    public int GetTypeId() => __ID__;
}
}