
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ActionsConfigCategory : Singleton<ActionsConfigCategory>
    {
        private readonly Dictionary<int, ActionsConfig> _dataMap;
        private readonly List<ActionsConfig> _dataList;

        public ActionsConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ActionsConfig>();
            _dataList = new List<ActionsConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ActionsConfig _v;
                _v = ActionsConfig.DeserializeActionsConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ActionsConfig> DataMap => _dataMap;
        public List<ActionsConfig> DataList => _dataList;

        public ActionsConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ActionsConfig Get(int key) => _dataMap[key];
        public ActionsConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
