//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class DifficultyHappyConfig : ProtoObject
{
    public DifficultyHappyConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        WaveNumber = _buf.ReadInt();
        HasSecond = _buf.ReadBool();
    }

    public static DifficultyHappyConfig DeserializeDifficultyHappyConfig(ByteBuf _buf)
    {
        return new DifficultyHappyConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 波数
    /// </summary>
    public int WaveNumber { get; set; }
    /// <summary>
    /// 是否有第二幕
    /// </summary>
    public bool HasSecond { get; set; }

    public const int __ID__ = 978946919;
    public int GetTypeId() => __ID__;
}
}