//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class HeroConfig : ProtoObject
{
    public HeroConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        HP = _buf.ReadLong();
        Atk = _buf.ReadInt();
        PhysicalDef = _buf.ReadInt();
        MagicDef = _buf.ReadInt();
        AtkInterval = _buf.ReadFloat();
        AtkRange = _buf.ReadInt();
        AtkType = _buf.ReadInt();
        this.EndInit();
    }

    public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
    {
        return new HeroConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 血量
    /// </summary>
    public long HP { get; set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public int Atk { get; set; }
    /// <summary>
    /// 护甲
    /// </summary>
    public int PhysicalDef { get; set; }
    /// <summary>
    /// 魔抗
    /// </summary>
    public int MagicDef { get; set; }
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public float AtkInterval { get; set; }
    /// <summary>
    /// 攻击范围
    /// </summary>
    public int AtkRange { get; set; }
    /// <summary>
    /// 攻击类型
    /// </summary>
    public int AtkType { get; set; }

    public const int __ID__ = -563759108;
    public int GetTypeId() => __ID__;
}
}