
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class HeroConfig : BeanBase
    {
        public HeroConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            HeroName = _buf.ReadString();
            HP = _buf.ReadLong();
            Atk = _buf.ReadInt();
            PhysicalDef = _buf.ReadInt();
            MagicDef = _buf.ReadInt();
            StrengthValue = _buf.ReadInt();
            AgileValue = _buf.ReadInt();
            MagicValue = _buf.ReadInt();
            MainType = (MainType)_buf.ReadInt();
            AtkInterval = _buf.ReadFloat();
            AtkRange = _buf.ReadInt();
            Speed = _buf.ReadFloat();
            AOIRange = _buf.ReadInt();
            ViewDistance = _buf.ReadLong();
            UnlockType = (UnlockType)_buf.ReadInt();
            ResourceName = _buf.ReadString();

            PostInit();
        }

        public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
        {
            return new HeroConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string HeroName;

        /// <summary>
        /// 血量
        /// </summary>
        public readonly long HP;

        /// <summary>
        /// 攻击力
        /// </summary>
        public readonly int Atk;

        /// <summary>
        /// 护甲
        /// </summary>
        public readonly int PhysicalDef;

        /// <summary>
        /// 魔抗
        /// </summary>
        public readonly int MagicDef;

        /// <summary>
        /// 力量属性
        /// </summary>
        public readonly int StrengthValue;

        /// <summary>
        /// 敏捷属性
        /// </summary>
        public readonly int AgileValue;

        /// <summary>
        /// 智力属性
        /// </summary>
        public readonly int MagicValue;

        public readonly MainType MainType;

        /// <summary>
        /// 攻击间隔
        /// </summary>
        public readonly float AtkInterval;

        /// <summary>
        /// 攻击范围
        /// </summary>
        public readonly int AtkRange;

        /// <summary>
        /// 移动速度
        /// </summary>
        public readonly float Speed;

        /// <summary>
        /// 视野范围
        /// </summary>
        public readonly int AOIRange;

        /// <summary>
        /// 视野范围
        /// </summary>
        public readonly long ViewDistance;

        public readonly UnlockType UnlockType;

        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string ResourceName;

        public const int __ID__ = -563759108;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "HeroName:" + HeroName + ","
            + "HP:" + HP + ","
            + "Atk:" + Atk + ","
            + "PhysicalDef:" + PhysicalDef + ","
            + "MagicDef:" + MagicDef + ","
            + "StrengthValue:" + StrengthValue + ","
            + "AgileValue:" + AgileValue + ","
            + "MagicValue:" + MagicValue + ","
            + "MainType:" + MainType + ","
            + "AtkInterval:" + AtkInterval + ","
            + "AtkRange:" + AtkRange + ","
            + "Speed:" + Speed + ","
            + "AOIRange:" + AOIRange + ","
            + "ViewDistance:" + ViewDistance + ","
            + "UnlockType:" + UnlockType + ","
            + "ResourceName:" + ResourceName + ","
            + "}";
        }

        partial void PostInit();
    }
}
