
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ModelCategory : Singleton<ModelCategory>
    {
        private readonly Dictionary<int, ModelConfig> _dataMap;
        private readonly List<ModelConfig> _dataList;

        public ModelCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ModelConfig>();
            _dataList = new List<ModelConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ModelConfig _v;
                _v = ModelConfig.DeserializeModelConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ModelConfig> DataMap => _dataMap;
        public List<ModelConfig> DataList => _dataList;

        public ModelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ModelConfig Get(int key) => _dataMap[key];
        public ModelConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
