
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterConfig : BeanBase
    {
        public MonsterConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            UnitConfigId = _buf.ReadInt();
            GroupId = _buf.ReadInt();
            HP = _buf.ReadLong();
            Atk = _buf.ReadInt();
            PhysicalDef = _buf.ReadInt();
            MagicDef = _buf.ReadInt();
            AtkInterval = _buf.ReadFloat();
            AtkRange = _buf.ReadInt();
            Speed = _buf.ReadFloat();
            AOIRange = _buf.ReadInt();
            Coin = _buf.ReadInt();
            Exp = _buf.ReadInt();
            OpenExtraBossNum = _buf.ReadInt();
            ExtraBossConfigId = _buf.ReadInt();
            ResourceName = _buf.ReadString();
            ViewDistance = _buf.ReadLong();

            PostInit();
        }

        public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
        {
            return new MonsterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// Unit配置Id
        /// </summary>
        public readonly int UnitConfigId;

        /// <summary>
        /// 组编号
        /// </summary>
        public readonly int GroupId;

        /// <summary>
        /// 血量
        /// </summary>
        public readonly long HP;

        /// <summary>
        /// 攻击力
        /// </summary>
        public readonly int Atk;

        /// <summary>
        /// 护甲
        /// </summary>
        public readonly int PhysicalDef;

        /// <summary>
        /// 魔抗
        /// </summary>
        public readonly int MagicDef;

        /// <summary>
        /// 攻击间隔
        /// </summary>
        public readonly float AtkInterval;

        /// <summary>
        /// 攻击范围
        /// </summary>
        public readonly int AtkRange;

        /// <summary>
        /// 移动速度
        /// </summary>
        public readonly float Speed;

        /// <summary>
        /// 视野范围
        /// </summary>
        public readonly int AOIRange;

        /// <summary>
        /// 击杀奖励金币
        /// </summary>
        public readonly int Coin;

        /// <summary>
        /// 击杀奖励经验值
        /// </summary>
        public readonly int Exp;

        public readonly int OpenExtraBossNum;

        public readonly int ExtraBossConfigId;

        public readonly string ResourceName;

        /// <summary>
        /// 视野范围
        /// </summary>
        public readonly long ViewDistance;

        public const int __ID__ = -55174244;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "GroupId:" + GroupId + ","
            + "HP:" + HP + ","
            + "Atk:" + Atk + ","
            + "PhysicalDef:" + PhysicalDef + ","
            + "MagicDef:" + MagicDef + ","
            + "AtkInterval:" + AtkInterval + ","
            + "AtkRange:" + AtkRange + ","
            + "Speed:" + Speed + ","
            + "AOIRange:" + AOIRange + ","
            + "Coin:" + Coin + ","
            + "Exp:" + Exp + ","
            + "OpenExtraBossNum:" + OpenExtraBossNum + ","
            + "ExtraBossConfigId:" + ExtraBossConfigId + ","
            + "ResourceName:" + ResourceName + ","
            + "ViewDistance:" + ViewDistance + ","
            + "}";
        }

        partial void PostInit();
    }
}
