
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MonsterGroupConfigCategory : Singleton<MonsterGroupConfigCategory>
    {
        private readonly Dictionary<int, MonsterGroupConfig> _dataMap;
        private readonly List<MonsterGroupConfig> _dataList;

        public MonsterGroupConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterGroupConfig>();
            _dataList = new List<MonsterGroupConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MonsterGroupConfig _v;
                _v = MonsterGroupConfig.DeserializeMonsterGroupConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MonsterGroupConfig> DataMap => _dataMap;
        public List<MonsterGroupConfig> DataList => _dataList;

        public MonsterGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public MonsterGroupConfig Get(int key) => _dataMap[key];
        public MonsterGroupConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
