
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum NoticeClientType
    {
        /// <summary>
        /// 不通知
        /// </summary>
        NoNotice = 0,

        /// <summary>
        /// 仅通知自己
        /// </summary>
        Self = 1,

        /// <summary>
        /// 广播AOI
        /// </summary>
        Broadcast = 2,

        /// <summary>
        /// 广播AOI，除自己外
        /// </summary>
        BroadcastWithoutSelf = 3,

    }
}
