
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class RandomNameCategory : Singleton<RandomNameCategory>
    {
        private readonly Dictionary<int, RandomName> _dataMap;
        private readonly List<RandomName> _dataList;

        public RandomNameCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, RandomName>();
            _dataList = new List<RandomName>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                RandomName _v;
                _v = RandomName.DeserializeRandomName(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, RandomName> DataMap => _dataMap;
        public List<RandomName> DataList => _dataList;

        public RandomName GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public RandomName Get(int key) => _dataMap[key];
        public RandomName this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
