
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class RandomName : BeanBase
    {
        public RandomName(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NameCN = _buf.ReadString();
            NameEN = _buf.ReadString();

            PostInit();
        }

        public static RandomName DeserializeRandomName(ByteBuf _buf)
        {
            return new RandomName(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 中文名称
        /// </summary>
        public readonly string NameCN;

        /// <summary>
        /// 英文名称
        /// </summary>
        public readonly string NameEN;

        public const int __ID__ = 2108921358;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NameCN:" + NameCN + ","
            + "NameEN:" + NameEN + ","
            + "}";
        }

        partial void PostInit();
    }
}
