//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class ResourceMonsterConfig : ProtoObject
{
    public ResourceMonsterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        HP = _buf.ReadLong();
        Atk = _buf.ReadInt();
        PhysicalDef = _buf.ReadInt();
        MagicDef = _buf.ReadInt();
        AtkInterval = _buf.ReadFloat();
        AtkRange = _buf.ReadInt();
        Speed = _buf.ReadInt();
        AOIRange = _buf.ReadInt();
        Coin = _buf.ReadInt();
        Exp = _buf.ReadInt();
        OpenExtraBossNum = _buf.ReadInt();
        ExtraBossConfigId = _buf.ReadInt();
        this.EndInit();
    }

    public static ResourceMonsterConfig DeserializeResourceMonsterConfig(ByteBuf _buf)
    {
        return new ResourceMonsterConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 血量
    /// </summary>
    public long HP { get; set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public int Atk { get; set; }
    /// <summary>
    /// 护甲
    /// </summary>
    public int PhysicalDef { get; set; }
    /// <summary>
    /// 魔抗
    /// </summary>
    public int MagicDef { get; set; }
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public float AtkInterval { get; set; }
    /// <summary>
    /// 攻击范围
    /// </summary>
    public int AtkRange { get; set; }
    /// <summary>
    /// 移动速度
    /// </summary>
    public int Speed { get; set; }
    /// <summary>
    /// 视野范围
    /// </summary>
    public int AOIRange { get; set; }
    /// <summary>
    /// 击杀奖励金币
    /// </summary>
    public int Coin { get; set; }
    /// <summary>
    /// 击杀奖励经验值
    /// </summary>
    public int Exp { get; set; }
    public int OpenExtraBossNum { get; set; }
    public int ExtraBossConfigId { get; set; }

    public const int __ID__ = 877342254;
    public int GetTypeId() => __ID__;
}
}