//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class StartZoneConfigCategory: Singleton<StartZoneConfigCategory>,IMerge
{
    private Dictionary<int, StartZoneConfig> _dataMap;
    private List<StartZoneConfig> _dataList;

    public StartZoneConfigCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, StartZoneConfig>();
        _dataList = new List<StartZoneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StartZoneConfig _v;
            _v = StartZoneConfig.DeserializeStartZoneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, StartZoneConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<StartZoneConfig> DataList => _dataList;

    public void Merge(object o)
    {
        StartZoneConfigCategory s = o as StartZoneConfigCategory;
        foreach (var kv in s._dataMap)
        {
            this._dataMap.Add(kv.Key, kv.Value);
        }
    }

    public StartZoneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartZoneConfig Get(int key) => _dataMap[key];
    public StartZoneConfig this[int key] => _dataMap[key];

    
    public string ConfigName()
    {
        return typeof(StartZoneConfig).Name;
    }
}
}