//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class StartMachineConfig : ProtoObject
{
    public StartMachineConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        InnerIP = _buf.ReadString();
        OuterIP = _buf.ReadString();
        WatcherPort = _buf.ReadString();
    }

    public static StartMachineConfig DeserializeStartMachineConfig(ByteBuf _buf)
    {
        return new StartMachineConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// 内网地址
    /// </summary>
    public string InnerIP { get; set; }
    /// <summary>
    /// 外网地址
    /// </summary>
    public string OuterIP { get; set; }
    /// <summary>
    /// 守护进程端口
    /// </summary>
    public string WatcherPort { get; set; }

    public const int __ID__ = 1628109127;
    public int GetTypeId() => __ID__;
}
}