
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UnitType
    {
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 0,

        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 1,

        /// <summary>
        /// NPC
        /// </summary>
        NPC = 2,

        /// <summary>
        /// 弹道
        /// </summary>
        Bullet = 3,

        /// <summary>
        /// 特效
        /// </summary>
        ParticleEffect = 4,

    }
}
