
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum UnlockType
    {
        /// <summary>
        /// 熟练度
        /// </summary>
        Proficiency = 0,

        /// <summary>
        /// 付费购买
        /// </summary>
        Pay = 1,

        /// <summary>
        /// 活动赠送
        /// </summary>
        Activity = 2,

        /// <summary>
        /// 碎片兑换
        /// </summary>
        ExchangeFragments = 3,

    }
}
