
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ZoneType
    {
        /// <summary>
        /// 游戏区
        /// </summary>
        Game = 0,

        /// <summary>
        /// 机器区
        /// </summary>
        Robot = 1,

        /// <summary>
        /// 路由区
        /// </summary>
        Router = 2,

    }
}
